teams:
  cluster-capacity-admins:
    description: Admin access to the cluster-capacity repo
    members:
    - ingvagabund
    privacy: closed
    repos:
      cluster-capacity: admin
  cluster-capacity-maintainers:
    description: Write access to the cluster-capacity repo
    members:
    - ingvagabund
    privacy: closed
    repos:
      cluster-capacity: write
  descheduler-admins:
    description: Admin access to the descheduler repo
    members:
    - damemi
    - ingvagabund
    # Emeritus:
    # - ravisantoshgudimetla
    privacy: closed
    repos:
      descheduler: admin
  descheduler-maintainers:
    description: Write access to the descheduler repo
    members:
    - a7i
    - damemi
    - ingvagabund
    - seanmalloy
    # Emeritus:
    # - ravisantoshgudimetla
    privacy: closed
    previously:
    - descehduler-maintainers
    repos:
      descheduler: write
  dra-driver-topology-admins:
    description: Admin access to the dra-driver-topology repo
    members:
    - dom4ha
    - johnbelamaric
    - klueska
    - lauralorenz
    - macsko
    - pohly
    - sanposhiho
    privacy: closed
    repos:
      dra-driver-topology: admin
  dra-driver-topology-maintainers:
    description: Write access to the dra-driver-topology repo
    members:
    - johnbelamaric
    - klueska
    - lauralorenz
    - pohly
    privacy: closed
    repos:
      dra-driver-topology: write
  kube-scheduler-simulator-admins:
    description: Admin access to the kube-scheduler-simulator
    members:
    - Huang-Wei
    - sanposhiho
    privacy: closed
    repos:
      kube-scheduler-simulator: admin
  kube-scheduler-wasm-extension-admins:
    description: Admin access to the kube-scheduler-wasm-extension
    members:
    - codefromthecrypt
    - kerthcet
    - sanposhiho
    privacy: closed
    repos:
      kube-scheduler-wasm-extension: admin
  kueue-admins:
    description: Admin access to the kueue repo
    members:
    - mimowo
    - tenzen-y
    privacy: closed
    repos:
      kueue: admin
  kueue-maintainers:
    description: Write access to the kueue repo
    members:
    - gabesaba
    - mimowo
    - tenzen-y
    privacy: closed
    repos:
      kueue: write
  kwok-admins:
    description: Admin access to the kwok repo
    members:
    - Huang-Wei
    - wzshiming
    privacy: closed
    repos:
      kwok: admin
  kwok-maintainers:
    description: Write access to the kwok repo
    members:
    - Huang-Wei
    - wzshiming
    privacy: closed
    repos:
      kwok: write
  scheduler-plugins-admins:
    description: Admin access to the scheduler-plugins repo
    members:
    - ahg-g
    - Huang-Wei
    privacy: closed
    repos:
      scheduler-plugins: admin
  scheduler-plugins-maintainers:
    description: Write access to the scheduler-plugins repo
    members:
    - ahg-g
    - Huang-Wei
    privacy: closed
    repos:
      scheduler-plugins: write
