teams:
  vsphere-csi-driver-admins:
    description: admin access to vsphere-csi-driver
    members:
    - divyenpatel
    privacy: closed
    repos:
      vsphere-csi-driver: admin
  vsphere-csi-driver-maintainers:
    description: write access to vsphere-csi-driver
    members:
    - divyenpatel
    - SandeepPissay
    - xing-yang
    privacy: closed
    repos:
      vsphere-csi-driver: write
