teams:
  karpenter-admins:
    description: admin access to the karpenter repo
    members:
    - adrianmoisey
    - bwagner5
    - ellistarn
    - gjtempleton
    - jackfrancis
    - jonathan-innis
    - njtran
    - towca
    - tzneal
    privacy: closed
    repos:
      karpenter: admin
  karpenter-maintainers:
    description: write access to the karpenter repo
    members:
    - adrianmoisey
    - bwagner5
    - ellistarn
    - gjtempleton
    - jackfrancis
    - jonathan-innis
    - njtran
    - towca
    - tzneal
    privacy: closed
    repos:
      karpenter: write
  karpenter-reviewers:
    description: read access to the karpenter repo
    members:
    - engedaam
    - jackfrancis
    - jmdeal      
    - tallaxes
    privacy: closed
    repos:
      karpenter: read
  karpenter-provider-ibm-cloud-admins:
    description: admin access to the karpenter-provider-ibm-cloud repo
    members:
    - pfeifferj
    privacy: closed
    repos:
      karpenter-provider-ibm-cloud: admin
  karpenter-provider-ibm-cloud-maintainers:
    description: write access to the karpenter-provider-ibm-cloud repo
    members:
    - pfeifferj
    privacy: closed
    repos:
      karpenter-provider-ibm-cloud: write
  sig-autoscaling-leads:
    description: "leads of the SIG Autoscaling"
    members:
    - adrianmoisey
    - gjtempleton
    - jackfrancis
    - towca
    privacy: closed
