teams:
  sig-auth-api-reviews:
    description: ""
    members:
    - deads2k
    - enj
    - liggitt
    privacy: closed
  sig-auth-bugs:
    description: ""
    members:
    - aramase
    - deads2k
    - enj
    - liggitt
    - micahhausler
    - ritazh
    privacy: closed
  sig-auth-feature-requests:
    description: ""
    members:
    - deads2k
    - enj
    - liggitt
    privacy: closed
  sig-auth-misc:
    description: ""
    members:
    - aramase
    - cjcullen
    - deads2k
    - enj
    - liggitt
    - micahhausler
    - ritazh
    privacy: closed
  sig-auth-pr-reviews:
    description: ""
    members:
    - deads2k
    - enj
    - liggitt
    privacy: closed
  sig-auth-proposals:
    description: ""
    members:
    - deads2k
    - enj
    - liggitt
    privacy: closed
  sig-auth-test-failures:
    description: ""
    members:
    - aramase
    - deads2k
    - enj
    - liggitt
    - micahhausler
    - ritazh
    privacy: closed
  sig-auth-leads:
    description: ""
    members:
    - aramase
    - deads2k
    - enj
    - liggitt
    - micahhausler
    - ritazh
    privacy: closed
