teams:
  sig-multicluster-api-reviews:
    description: ""
    members:
    - mwielgus
    privacy: closed
  sig-multicluster-bugs:
    description: ""
    members:
    - mwielgus
    privacy: closed
  sig-multicluster-feature-requests:
    description: ""
    members:
    - derekwaynecarr
    - mwielgus
    - smarterclayton
    privacy: closed
  sig-multicluster-misc:
    description: 'SIG for multi cluster: https://groups.google.com/forum/#!forum/kubernetes-sig-multicluster'
    members:
    - derekwaynecarr
    - liggitt
    - mwielgus
    - smarterclayton
    privacy: closed
  sig-multicluster-pr-reviews:
    description: ""
    members:
    - mwielgus
    privacy: closed
  sig-multicluster-proposals:
    description: ""
    members:
    - derekwaynecarr
    - liggitt
    - mwielgus
    - smarterclayton
    previously:
    - sig-mutlicluster-proposals
    privacy: closed
  sig-multicluster-test-failures:
    description: ""
    members:
    privacy: closed
  sig-multicluster-leads:
    description: ""
    members:
    - jeremyot
    - skitt
    privacy: closed
