teams:
  provider-azure:
    description: General discussion for SIG Azure
    members:
    - andyzhangx
    - brendandburns
    - feiskyer
    - justaugustus
    - nilo19
    - ritazh
    privacy: closed
    previously:
    - sig-azure
