teams:
  depstat-admins:
    description: Admin access to depstat repo
    maintainers:
    - nikhita
    members:
    - dims
    - navidshaikh
    - RinkiyaKeDad
    privacy: closed
    repos:
      depstat: admin
  apisnoop-admins:
    description: Admin access to apisnoop repo
    members:
    - BobyMCbobs
    - cooldracula
    - heyste
    - koksay
    - mfahlandt
    - xmudrii
    privacy: closed
    repos:
      apisnoop: admin
  apisnoop-maintainers:
    description: Write access to apisnoop repo
    members:
    - BobyMCbobs
    - cooldracula
    - heyste
    - koksay
    - mfahlandt
    - xmudrii
    privacy: closed
    repos:
      apisnoop: write
  maintainer-tools-admins:
    description: admin access to the maintainer-tools repo
    members:
    - ameukam
    - dims
    - johnbelamaric
    - justinsb
    - thockin
    privacy: closed
    repos:
      maintainer-tools: admin
  verify-conformance-admins:
    description: admin access to the verify-conformance repo
    members:
    - BobyMCbobs
    - heyste
    - koksay
    - mfahlandt
    - xmudrii
    privacy: closed
    repos:
      verify-conformance: admin
  wg-device-management-admins:
    description: Admin access to wg-device-management repo
    members:
    - johnbelamaric
    - klueska
    - pohly
    privacy: closed
    repos:
      wg-device-management: admin
  wg-device-management-maintainers:
    description: Write access to wg-device-management repo
    members:
    - johnbelamaric
    - klueska
    - pohly
    privacy: closed
    repos:
      wg-device-management: write
  wg-serving-admins:
    description: Admin access to the wg-serving repo
    members:
    - ArangoGutierrez
    - Jeffwan
    - SergeyKanzhelev
    - terrytangyuan
    privacy: closed
    repos:
      wg-serving: admin
