teams:
  inference-perf-admins:
    description: Admin access to the inference-perf repo
    members:
    - achandrasekar
    - SachinVarghese
    - terrytangyuan
    - wangchen615
    privacy: closed
    repos:
      inference-perf: admin
  inference-perf-maintainers:
    description: Write access to the inference-perf repo
    members:
    - achandrasekar
    - SachinVarghese
    - terrytangyuan
    - wangchen615
    privacy: closed
    repos:
      inference-perf: write
