teams:
  headlamp-admins:
    description: Admin access to the headlamp repo
    members:
    - joaquimrocha
    privacy: closed
    repos:
      headlamp: admin
  headlamp-maintainers:
    description: Write access to the headlamp repo
    members:
    - illume
    - joaquimrocha
    - sniok
    privacy: closed
    repos:
      headlamp: maintain
  headlamp-reviewers:
    description: Triage access to the headlamp repo
    members:
    - ashu8912
    - knrt10
    - skoeva
    - vyncent-t
    - yolossn
    privacy: closed
    repos:
      headlamp: write
