teams:
  headlamp-admins:
    description: Admin access to the headlamp repo
    members:
    - joaquimrocha
    privacy: closed
    repos:
      headlamp: admin
  headlamp-maintainers:
    description: Write access to the headlamp repo
    members:
    - joaquimrocha
    - sniok
    - illume
    privacy: closed
    repos:
      headlamp: maintain
