teams:
  about-api-admins:
    description: admin access for the about-api repo
    members:
    - jeremyot
    - skitt
    privacy: closed
    repos:
      about-api: admin
  cluster-inventory-api-admins:
    description: Admin access for cluster-inventory-api repo
    members:
    - dixudx
    - mikeshng
    - RainbowMango
    privacy: closed
    repos:
      cluster-inventory-api: admin
  federation-wg:
    description: Individuals who are part of sig-multicluster and working as federation
      workgroup.
    members:
    - hectorj2f
    - jimmidyson
    - quinton-hoole
    privacy: closed
  mcs-api-admins:
    description: Admin access to the mcs-api repo
    members:
    - JeremyOT
    - skitt
    privacy: closed
    repos:
      mcs-api: admin
  sig-multicluster-site-admins:
    description: Admin access to the sig-multicluster-site repo
    members:
    - jeremyot
    - lauralorenz
    - skitt
    privacy: closed
    repos:
      sig-multicluster-site: admin
  sig-multicluster-site-maintainers:
    description: Write access to the sig-multicluster-site repo
    members:
    - jeremyot
    - lauralorenz
    - skitt
    privacy: closed
    repos:
      sig-multicluster-site: write
  work-api-admins:
    description: Admin access for the work-api repo
    members:
    - jeremyot
    - skitt
    privacy: closed
    repos:
      work-api: admin
  multicluster-runtime-admins:
    description: Admin access for the multicluster-runtime repo
    members:
    - jeremyot
    - skitt
    - sttts
    privacy: closed
    repos:
      multicluster-runtime: admin
  multicluster-runtime-maintainers:
    description: Write access for the multicluster-runtime repo
    members:
    - jeremyot
    - skitt
    - sttts
    privacy: closed
    repos:
      multicluster-runtime: write
