teams:
  node-problem-detector-admins:
    description: Admin access to the node-problem-detector repo
    members:
    - dchen1107
    - hakman
    - Random-Liu
    - wangzhen127
    privacy: closed
    repos:
      node-problem-detector: admin
  node-problem-detector-maintainers:
    description: Write access to the node-problem-detector repo. This group manages releases.
    members:
    - andyxning
    - dchen1107
    - hakman
    - Random-Liu
    - wangzhen127
    privacy: closed
    repos:
      node-problem-detector: write
  sig-node-api-reviews:
    description: API Reviews for Kubernetes Node Special-Interest-Group
    members:
    - dchen1107
    - derekwaynecarr
    - smarterclayton
    - tallclair
    - thockin
    privacy: closed
  sig-node-leads:
    description: Chairs and Technical Leads for SIG Node
    members:
    - dchen1107
    - derekwaynecarr
    - haircommander
    - mrunalp
    - SergeyKanzhelev
    privacy: closed
  sig-node-bugs:
    description: Bugs for Kubernetes Node Special-Interest-Group
    members:
    - andrewsykim
    - bobbypage
    - dchen1107
    - derekwaynecarr
    - dims
    - endocrimes
    - feiskyer
    - harche
    - kannon92
    - klueska
    - krmayankk
    - kwilczynski
    - matthyx
    - mrunalp
    - mtaufen
    - odinuge
    - pacoxu
    - Random-Liu
    - saschagrunert
    - SergeyKanzhelev
    - sjenning
    - wzshiming
    privacy: closed
  sig-node-feature-requests:
    description: Feature Requests for Kubernetes Node Special-Interest-Group
    members:
    - andrewsykim
    - bobbypage
    - dchen1107
    - derekwaynecarr
    - dims
    - endocrimes
    - feiskyer
    - harche
    - klueska
    - krmayankk
    - kwilczynski
    - matthyx
    - mrunalp
    - mtaufen
    - odinuge
    - pacoxu
    - Random-Liu
    - saschagrunert
    - SergeyKanzhelev
    - sjenning
    - wzshiming
    privacy: closed
  sig-node-pr-reviews:
    description: PR Reviews for Kubernetes Node Special-Interest-Group
    members:
    - andrewsykim
    - bobbypage
    - dchen1107
    - derekwaynecarr
    - dims
    - endocrimes
    - feiskyer
    - harche
    - kannon92
    - klueska
    - krmayankk
    - kwilczynski
    - matthyx
    - mrunalp
    - mtaufen
    - odinuge
    - pacoxu
    - Random-Liu
    - saschagrunert
    - SergeyKanzhelev
    - sjenning
    - wzshiming
    privacy: closed
  sig-node-proposals:
    description: Proposals for Kubernetes Node Special-Interest-Group
    members:
    - andrewsykim
    - bobbypage
    - dchen1107
    - derekwaynecarr
    - dims
    - endocrimes
    - feiskyer
    - harche
    - klueska
    - krmayankk
    - kwilczynski
    - matthyx
    - mrunalp
    - mtaufen
    - odinuge
    - pacoxu
    - Random-Liu
    - saschagrunert
    - SergeyKanzhelev
    - sjenning
    - wzshiming
    privacy: closed
  sig-node-test-failures:
    description: Test Failures for Kubernetes Node Special-Interest-Group
    members:
    - bart0sh
    - bobbypage
    - dchen1107
    - derekwaynecarr
    - endocrimes
    - harche
    - kannon92
    - klueska
    - mrunalp
    - Random-Liu
    - saschagrunert
    - SergeyKanzhelev
    - sjenning
    privacy: closed
  sig-node-cri-o-test-maintainers:
    description: Maintainers of CRI-O related tests for the Kubernetes Node Special-Interest-Group
    members:
    - haircommander
    - harche
    - kannon92
    - kwilczynski
    - mrunalp
    - rphillips
    - sairameshv
    - saschagrunert
    - sohankunkerkar
    privacy: closed
