teams:
  wg-naming:
    description: WG Naming
    members:
    - justaugustus
    privacy: closed
    teams:
      wg-naming-leads:
        description: WG Naming Leads
        members:
        - justaugustus
        privacy: closed
